/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 24-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Common;
using GameRevision.GW2Emu.Common.Math;
using GameRevision.GW2Emu.Common.Session;
using GameRevision.GW2Emu.Common.Messaging;
using GameRevision.GW2Emu.Common.Serialization;

namespace GameRevision.GW2Emu.LoginServer.Messages.CtoS
{
    public class P02_ComputerUserName : GenericMessage
    {
        public string Username;
        public string ComputerName;
        
        public override ushort Header
        {
            get
            {
                return 2;
            }
        }
        
        public override void Deserialize(Deserializer deserializer)
        {
            this.Username = deserializer.ReadUtf16String();
            this.ComputerName = deserializer.ReadUtf16String();
        }
    }
}
