/*
 * This code was autogenerated by
 * GameRevision.GW2Emu.CodeWriter.
 * Date generated: 24-07-13
 */

using System;
using System.IO;
using System.Net;
using GameRevision.GW2Emu.Common;
using GameRevision.GW2Emu.Common.Math;
using GameRevision.GW2Emu.Common.Session;
using GameRevision.GW2Emu.Common.Messaging;
using GameRevision.GW2Emu.Common.Serialization;

namespace GameRevision.GW2Emu.LoginServer.Messages.CtoS
{
    public class P29_EnterWorld : GenericMessage
    {
        public int AuthInc;
        public int Type;
        public int Unknown2;
        public int MapID;
        public int Unknown4;
        
        public override ushort Header
        {
            get
            {
                return 29;
            }
        }
        
        public override void Deserialize(Deserializer deserializer)
        {
            this.AuthInc = deserializer.ReadVarint();
            this.Type = deserializer.ReadVarint();
            this.Unknown2 = deserializer.ReadVarint();
            this.MapID = deserializer.ReadVarint();
            this.Unknown4 = deserializer.ReadVarint();
        }
    }
}
